include: package:flutter_lints/flutter.yaml

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options

analyzer:
  exclude:
    - "**/*.g.dart"
    - "lib/generated/**"
    - "lib/bindings/**"
  errors:
    constant_identifier_names: ignore

# Ignore specific rules in specific files
# https://dart.dev/guides/language/analysis-options#suppressing-rules-for-a-file
linter:
  rules:
    constant_identifier_names: true
