name: dart_wallet_core_codegen
description: "A new Flutter package project."
version: 0.0.1

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  convert: 3.1.2
  ffi: 2.1.3
  fixnum: 1.1.1
  flutter:
    sdk: flutter
  protobuf: 4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  ffigen: 18.1.0

############################################################

ffigen:
  output: "lib/bindings/bindings.dart"

  name: "WCB"
  sort: true
  description: "Trust Wallet Core Binding To Dart."

  enums:
    as-int:
      include:
        - TWAESPaddingMode
        - TWBitcoinSigHashType
        - TWBlockchain
        - TWCoinType
        - TWCurve
        - TWDerivation
        - TWFilecoinAddressType
        - TWFiroAddressType
        - TWHDVersion
        - TWHRP
        - TWPublicKeyType
        - TWPurpose
        - TWStoredKeyEncryption
        - TWStoredKeyEncryptionLevel

  comments:
    style: doxygen
    length: full
  headers:
    entry-points:
      - "./include/**.h"
